#AMBIENTE VIRTUAL(VENV)
#python -m venv nome-do-ambiente(venv)

#PARA ATIVAR O VENV
#.\venv\Scripts\Activate.ps1

#PARA DESATIVAR
#deactivate


#PARA LIMPAR O TERMINAL
#-Ctrl+L


#PACOTES
#-INSTALAR
#pip install pacote


#pip freeze (para congelar os pacotes com suas verções)

#pip requests(pacote de instalar)

#pip freeze > arquivo.txt(escreve em um arquivo o que iria só printar) ao invés de arquivo --> requirements.txt


#RECUPERAR(DESCONGELAR)
#pip install -r requirements.txt

#PARA ESCONDER ALGUNS ARQUIVOS
#.gitignore(escreve venv dentro)

#COMANDOS PARA DAR COMIT
#git config --global user.name"nome"
#git config --global user.email"email"
#git config --list
